import Link from 'next/link'
import { Button } from '@/components/ui/button'

export default function MarketingPage() {
  return (
    <div className="min-h-screen bg-bg">
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-primary opacity-10" />
        <div className="relative container mx-auto px-4 py-20 text-center">
          <h1 className="text-5xl md:text-7xl font-bold text-txt mb-6">
            Transform Your Fitness with
            <span className="bg-gradient-primary bg-clip-text text-transparent">
              {" "}AI
            </span>
          </h1>
          <p className="text-xl md:text-2xl text-muted mb-8 max-w-3xl mx-auto">
            Get personalized workout plans generated by AI, track your progress, and achieve your fitness goals faster than ever before.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button asChild size="lg" className="bg-primary hover:bg-primary/90 text-white shadow-glow">
              <Link href="/onboarding">
                Start Your Journey
              </Link>
            </Button>
            <Button asChild variant="outline" size="lg" className="border-border hover:bg-surface">
              <Link href="/about">
                Learn More
              </Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-surface">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl md:text-4xl font-bold text-center text-txt mb-16">
            Why Choose CreatiFit AI?
          </h2>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="text-center p-6">
              <div className="w-16 h-16 bg-gradient-primary rounded-full mx-auto mb-4 flex items-center justify-center">
                <span className="text-2xl">🤖</span>
              </div>
              <h3 className="text-xl font-semibold text-txt mb-3">AI-Powered Plans</h3>
              <p className="text-muted">
                Get personalized workout plans tailored to your goals, equipment, and fitness level.
              </p>
            </div>
            <div className="text-center p-6">
              <div className="w-16 h-16 bg-gradient-accent rounded-full mx-auto mb-4 flex items-center justify-center">
                <span className="text-2xl">📱</span>
              </div>
              <h3 className="text-xl font-semibold text-txt mb-3">Mobile First</h3>
              <p className="text-muted">
                Access your workouts anywhere with our mobile-optimized platform.
              </p>
            </div>
            <div className="text-center p-6">
              <div className="w-16 h-16 bg-gradient-primary rounded-full mx-auto mb-4 flex items-center justify-center">
                <span className="text-2xl">📊</span>
              </div>
              <h3 className="text-xl font-semibold text-txt mb-3">Track Progress</h3>
              <p className="text-muted">
                Monitor your performance with detailed analytics and progress tracking.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-bg">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-txt mb-6">
            Ready to Transform Your Fitness?
          </h2>
          <p className="text-xl text-muted mb-8 max-w-2xl mx-auto">
            Join thousands of users who have already achieved their fitness goals with CreatiFit AI.
          </p>
          <Button asChild size="lg" className="bg-primary hover:bg-primary/90 text-white shadow-glow text-lg px-8 py-4">
            <Link href="/onboarding">
              Get Started Now
            </Link>
          </Button>
        </div>
      </section>
    </div>
  )
}
