import { AppHeader } from "@/components/ui/app-header";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export default function MarketingPage() {
  return (
    <div className="min-h-screen bg-bg">
      <AppHeader />
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-primary opacity-10" />
        <div className="relative container mx-auto px-4 sm:px-6 py-12 md:py-20 text-center">
          <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold text-txt mb-4 md:mb-6">
            Transform Your Fitness with
            <span className="bg-gradient-primary bg-clip-text text-transparent">
              {" "}
              AI
            </span>
          </h1>
          <p className="text-lg sm:text-xl md:text-2xl text-muted mb-6 md:mb-8 max-w-3xl mx-auto px-2">
            Get personalized workout plans generated by AI, track your progress,
            and achieve your fitness goals faster than ever before.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center px-4">
            <Button
              asChild
              size="lg"
              className="bg-primary hover:bg-primary/90 text-white shadow-glow w-full sm:w-auto"
            >
              <Link href="/onboarding">Start Your Journey</Link>
            </Button>
            <Button
              asChild
              variant="outline"
              size="lg"
              className="border-border hover:bg-surface w-full sm:w-auto"
            >
              <Link href="/dashboard">Go to Dashboard</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-12 md:py-20 bg-surface">
        <div className="container mx-auto px-4 sm:px-6">
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-center text-txt mb-8 md:mb-16">
            Why Choose CreatiFit AI?
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">
            <div className="text-center p-4 md:p-6">
              <div className="w-14 h-14 md:w-16 md:h-16 bg-gradient-primary rounded-full mx-auto mb-3 md:mb-4 flex items-center justify-center">
                <span className="text-xl md:text-2xl">🤖</span>
              </div>
              <h3 className="text-lg md:text-xl font-semibold text-txt mb-2 md:mb-3">
                AI-Powered Plans
              </h3>
              <p className="text-sm md:text-base text-muted px-2">
                Get personalized workout plans tailored to your goals,
                equipment, and fitness level.
              </p>
            </div>
            <div className="text-center p-4 md:p-6">
              <div className="w-14 h-14 md:w-16 md:h-16 bg-gradient-accent rounded-full mx-auto mb-3 md:mb-4 flex items-center justify-center">
                <span className="text-xl md:text-2xl">📱</span>
              </div>
              <h3 className="text-lg md:text-xl font-semibold text-txt mb-2 md:mb-3">
                Mobile First
              </h3>
              <p className="text-sm md:text-base text-muted px-2">
                Access your workouts anywhere with our mobile-optimized
                platform.
              </p>
            </div>
            <div className="text-center p-4 md:p-6">
              <div className="w-14 h-14 md:w-16 md:h-16 bg-gradient-primary rounded-full mx-auto mb-3 md:mb-4 flex items-center justify-center">
                <span className="text-xl md:text-2xl">📊</span>
              </div>
              <h3 className="text-lg md:text-xl font-semibold text-txt mb-2 md:mb-3">
                Track Progress
              </h3>
              <p className="text-sm md:text-base text-muted px-2">
                Monitor your performance with detailed analytics and progress
                tracking.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-12 md:py-20 bg-bg">
        <div className="container mx-auto px-4 sm:px-6 text-center">
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-txt mb-4 md:mb-6">
            Ready to Transform Your Fitness?
          </h2>
          <p className="text-lg md:text-xl text-muted mb-6 md:mb-8 max-w-2xl mx-auto px-2">
            Join thousands of users who have already achieved their fitness
            goals with CreatiFit AI.
          </p>
          <Button
            asChild
            size="lg"
            className="bg-primary hover:bg-primary/90 text-white shadow-glow text-lg px-6 md:px-8 py-3 md:py-4 w-full sm:w-auto"
          >
            <Link href="/onboarding">Get Started Now</Link>
          </Button>
        </div>
      </section>
    </div>
  );
}
